GET http://localhost:3000/api/jokes


###
POST http://localhost:3000/api/jokes
Content-Type: application/json

{
    "title": "Hippo ",
    "content": "Why don't you find hippopotamuses hiding in trees? They're really good at it.",
    "authorId": 1
}