GET http://localhost:5000/api/jokes
###
GET http://localhost:5000/api/users
###
GET http://localhost:5000/api/jokes/3


###
POST http://localhost:5000/api/jokes
Content-Type: application/json

{
    "title": "Hippo ",
    "content": "Why don't you find hippopotamuses hiding in trees? They're really good at it.",
    "authorId": 1
}

###
DELETE http://localhost:5000/api/jokes/2

###

PATCH http://localhost:5000/api/jokes/3
Content-Type: application/json

{
    "title": "Hippopotamusssss",
    "content": "Why don't hippos like fast food? Because they can't catch it!",
    "authorId": 1
}

###
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "firstName": "Hippo",
    "lastName":"Litto",
    "email": "demo@user.io",
    "password": "password"
}


###
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "firstName": "MonsterGame",
    "lastName":"Litto",
    "email": "monster@gmail.com",
    "password": "password"
}

###
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email": "monster@gmail.com",
    "password": "passwrd"
}