GET http://localhost:5000/api/gghgh
###
GET http://localhost:5000/api/users
###
GET http://localhost:5000/api/jokes/6

###
DELETE http://localhost:5000/api/jokes/6

###
POST http://localhost:5000/api/jokes
Content-Type: application/json

{
    "title": "Hippo ",
    "content": "Why don't you find hippopotamuses hiding in trees? They're really good at it.",
    "authorId": 1
}

###
DELETE http://localhost:5000/api/jokes/2

###

PATCH http://localhost:5000/api/jokes/3
Content-Type: application/json

{
    "title": "Hippopotamusssss",
    "content": "Why don't hippos like fast food? Because they can't catch it!",
    "authorId": 1
}

###
POST http://localhost:5000/api/users/register
Content-Type: application/json
CSRF-TOKEN: vgvE1ExM-ogyPuqPiQZKloJOl8NyRpwXoFJ8

{
    "firstName": "Youwen",
    "lastName":"Zhu",
    "email": "youwenzhu@gmail.com",
    "password": "123"
}

###
POST http://localhost:5000/api/users/login
Content-Type: application/json
CSRF-TOKEN: vgvE1ExM-ogyPuqPiQZKloJOl8NyRpwXoFJ8


{
    "email": "DafitriS@gmail.com",
    "password": "Dassword"
}

###
GET http://localhost:5000/api/csrf/restore

# "user": {
#     "id": 7,
#     "firstName": "Dafitri",
#     "email": "DafitriS@gmail.com"
#   },
#   "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZmlyc3ROYW1lIjoiRGFmaXRyaSIsImVtYWlsIjoiRGFmaXRyaVNAZ21haWwuY29tIiwiaWF0IjoxNjkxOTY5NTczLCJleHAiOjE2OTE5NzMxNzN9.2Ynt6ubzXQIVtJdVF9yKSNqRXxE0BveqPjeK0SQVS_U"

###
GET http://localhost:5000/api/users/current
Content-Type: application/json
CSRF-Token: q1chT9fb-WsG72pimilpKW-vtku_MLvZc4Ps
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZmlyc3ROYW1lIjoiRGFmaXRyaSIsImVtYWlsIjoiRGFmaXRyaVNAZ21haWwuY29tIiwiaWF0IjoxNjkxOTcyMzA5LCJleHAiOjE2OTE5NzU5MDl9.eofSeXb1jHojT9kPrtlui655w6nhYkzyPb9E7M4UBC8
